### ISSUE TITLE
Update 1.15.1

### ISSUE THREAD

**Issue by Momonche** [SirBlobman/CooldownsX#1]
Hello !
When I use your plugin on 1.15.1, there is this error spamming the console.

[SirBlobmanAPI] Could not find valid NMS handler for '1_15_R1'. Using fallback handler...

EnderPearl-Coolddown version 3.3
Server: git-Paper-33 (MC 1.15.1)

**Comment by SirBlobman** [comment]
1.15.1 is not supported yet, this will be fixed soon

**Comment by Momonche** [comment]
Ok thanks !

**Comment by Momonche** [comment]
Version 4.0.0 works fine !

Thanks !
