### ISSUE TITLE
JAR files and weapon cooldown suggestions.

### ISSUE THREAD

**Issue by IceeFoox** [SirBlobman/CooldownsX#29]
Can you add a jar file to Gihub?

And is it possible to add a weapon cooldown for 1.8.8?

**Comment by SirBlobman** [comment]
- File downloads are provided on SpigotMC (Releases): https://www.spigotmc.org/resources/41981/
- Beta downloads are provided on my Jenkins CI: https://jenkins.sirblobman.xyz/job/SirBlobman/job/CooldownsX
- Weapon cooldowns will likely not be added.
