### ISSUE TITLE
Feature: Work with PvP manager to have a cooldown for when tagged in pvp & one for normal

### ISSUE THREAD

**Issue by TomLewis** [SirBlobman/CooldownsX#3]
Requesting to have 2 cooldowns, 1 for Global use (Default could be 2 seconds)
and another for when tagged in PvP (Say 15 seconds).

Then you can have Ender pearl building/PvP.

https://www.spigotmc.org/resources/pvpmanager-lite.845/

**Comment by SirBlobman** [comment]
Thanks for the suggestion, I'll consider adding support for combat plugins for the next update

**Comment by TomLewis** [comment]
Did this ever happen?

**Comment by Parthodys** [comment]
Any progress on this?

**Comment by TomLewis** [comment]
@SirBlobman this would still be very much appreciated to be added!

**Comment by SirBlobman** [comment]
@TomLewis @Caleston Added in 4.4.0.140, but for CombatLogX.

**Comment by TomLewis** [comment]
Bumping again, as PvPManager added cooldowns for end pearls recently while tagged, but its conflicting a bit with your plugin:
CooldownsX is set to 5s cooldown for ender pearls and the PvP manager plugin is set to 15s when tagged, this is the behavior I wanted from the initial ticket, but the display of the text is wrong, its repeating 5s over and over until 15s has passed.

![2023-03-18_10 56 12](https://user-images.githubusercontent.com/144046/226101932-bb769edf-2359-4131-9b12-5bd50e330bdf.png)
