### ISSUE TITLE
Golden Apple Cool Down

### ISSUE THREAD

**Issue by iDirtniverse** [SirBlobman/CooldownsX#4]
Hey, can you also add a golden apple cooldown too? this plugin is super awesome!

**Comment by SirBlobman** [comment]
Once CooldownsX is released a golden apple cooldown will be added :)

**Comment by Momonche** [comment]
@SirBlobman Can you add an option to add a Cooldown on ENCHANTED_GOLDEN_APPLE and another for GOLDEN_APPLE ?, actually it's the same cooldown

**Comment by SirBlobman** [comment]
See #5 for the solution.
