### ISSUE TITLE
Suggestion: Add shared cooldown for all potion types

### ISSUE THREAD

**Issue by Parthodys** [SirBlobman/CooldownsX#7]
It currently seems to separate basic potions / splash potions / lingering potions into different cooldowns, allowing players to avoid a cooldown by switching potion type.

Could a way to make all potion types share the same cooldown be added?

**Comment by Parthodys** [comment]
I suppose this could have been maybe reported as a bug as well @SirBlobman

**Comment by SirBlobman** [comment]
Should be possible with version 4.4.0.140.
