### ISSUE TITLE
Suggestion: Multiple cooldowns in the actionbar

### ISSUE THREAD

**Issue by florensm** [SirBlobman/CooldownsX#8]
Would be so cool if you could add more cooldowns in one actionbar, so you could have it like the following: Pearl: <pearlcooldown> Gapple: <gapplecooldown> Combat: <combattime> (Would be even cooler if you could make it link with combatlogx so i can also add the combattime with it. :) )

**Comment by SirBlobman** [comment]
Multiple cooldowns should be possible with a third-party action bar manager and the PlaceholderAPI placeholders provided by CooldownsX.
